version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./music:/usr/share/nginx/html/music
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
      - "8003:8003"

  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    volumes:
      - .httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "8080:80"
      - "8009:8003"