FROM alpine
RUN apk update && \
    apk add nginx && \
    rm -rf /var/cache/apk/*
RUN mkdir -p /etc/nginx/
COPY nginx.conf /etc/nginx/nginx.conf
COPY music/ /usr/share/nginx/html/music
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80
CMD nginx -g 'daemon off;'
#./nginx.conf:/etc/nginx/nginx.conf
#      - ./music:/usr/share/nginx/html/music
#      - ./index.html:/usr/share/nginx/html/index.html