FROM golang:1.20.1-alpine AS builder
WORKDIR /app
COPY /var/lib/jenkins/HomeWorkRepo/main.go ./
RUN go build main.go

FROM alpine
COPY --from=builder /app/main /app/main
EXPOSE 8003
CMD /bin/sh -c "/app/main"
